name: Feature Request
description: Use this template if you want to request a new function!
title: "[FEAT/EN] <Replace this with a brief title and keep the [tag] remain.>"
labels: 
  - New
  - imagine / 设想
assignees: 
  - fr1g
body:
  - type: markdown
    attributes:
      value: |
        Before you start, you must confirm:
        
        - You are using the latest version of LauncherX from the current channel.
        - You have already checked the [CSKB](https://kb.corona.studio/zhCN/lxguide/startup/) or other channels and confirmed that LauncherX indeed doesn't have such a feature (or it's not good enough yet).
        - Your request doesn't duplicate any existing issues, and the feature you're requesting has a reasonable potential user base.

  - type: checkboxes
    id: check
    attributes:
      label: Confirmation
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues and found no similar requests.
          required: true

        - label: I confirm I'm using the latest version of LauncherX in the current channel, and the feature I need is either missing or could be improved.
          required: true

        - label: I'm willing to discuss this in the community chat group if needed.

  - type: textarea
    id: function_description
    attributes:
      label: What kind of feature is this?
      description: "If your request is too broad, it should be split into multiple separate issues."
    validations:
      required: true

  - type: textarea
    id: reason_for_feature
    attributes:
      label: Why is this feature needed?
      description: "Will this feature provide significant convenience?"
    validations:
      required: true

  - type: textarea
    id: usage_frequency
    attributes:
      label: How often would you personally perform such operations? Does this feature really need to be implemented in the launcher?
      description: "Be honest with yourself (hmm)"
    validations:
      required: true

  - type: textarea
    id: related_images
    attributes:
      label: Related Images
      description: "You can directly upload or Ctrl+V paste here. These could be mockups made with software or HTML, less abstract hand-drawn sketches, or annotated screenshots of LauncherX."
    validations:
      required: true
  
  - type: textarea
    id: additional
    attributes: 
      label: Additional Information
      description: |
        Write other relevant content here.
        
        If you're in the LauncherX community chat group, you can leave your group nickname here so we can reach out for real-time discussion if needed.